// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBihDPXnz26MteiuFmBGWIz4RpDmej8hM4',
    appId: '1:95867617686:web:ae5c6c318d861eae059db7',
    messagingSenderId: '95867617686',
    projectId: 'ceramic-cafe-client',
    authDomain: 'ceramic-cafe-client.firebaseapp.com',
    storageBucket: 'ceramic-cafe-client.firebasestorage.app',
    measurementId: 'G-T42CVESDZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3T46q2Yh5arneWecKRbhefsbbHttnpZ8',
    appId: '1:95867617686:android:5938ac762ff5d2d7059db7',
    messagingSenderId: '95867617686',
    projectId: 'ceramic-cafe-client',
    storageBucket: 'ceramic-cafe-client.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVWuWRdXAYlumT_n0I1XK5brHAnQUvBI',
    appId: '1:95867617686:ios:b4ef972b89929600059db7',
    messagingSenderId: '95867617686',
    projectId: 'ceramic-cafe-client',
    storageBucket: 'ceramic-cafe-client.firebasestorage.app',
    iosBundleId: 'com.example.studiohCeramicCafeClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVWuWRdXAYlumT_n0I1XK5brHAnQUvBI',
    appId: '1:95867617686:ios:b4ef972b89929600059db7',
    messagingSenderId: '95867617686',
    projectId: 'ceramic-cafe-client',
    storageBucket: 'ceramic-cafe-client.firebasestorage.app',
    iosBundleId: 'com.example.studiohCeramicCafeClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBihDPXnz26MteiuFmBGWIz4RpDmej8hM4',
    appId: '1:95867617686:web:75ad9da5c1e0f58e059db7',
    messagingSenderId: '95867617686',
    projectId: 'ceramic-cafe-client',
    authDomain: 'ceramic-cafe-client.firebaseapp.com',
    storageBucket: 'ceramic-cafe-client.firebasestorage.app',
    measurementId: 'G-RGX0JZRTF4',
  );
}
