// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwsSXJbKu8JaI6xD5EJDSBHVUzz-Dz374',
    appId: '1:646227080671:web:645c11cc680e82a815006a',
    messagingSenderId: '646227080671',
    projectId: 'opportune-ego-460309-u3',
    authDomain: 'opportune-ego-460309-u3.firebaseapp.com',
    storageBucket: 'opportune-ego-460309-u3.firebasestorage.app',
    measurementId: 'G-77VMY1L5SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUVGJT0bhnlKi2XUJaSXn9hSuYzuIbHyE',
    appId: '1:646227080671:android:fc963b0ba4c0d24115006a',
    messagingSenderId: '646227080671',
    projectId: 'opportune-ego-460309-u3',
    storageBucket: 'opportune-ego-460309-u3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxNJM0lIDY7Ge7E9eR2QjGG7qIWuPtkBc',
    appId: '1:646227080671:ios:3444c73d7e39c29415006a',
    messagingSenderId: '646227080671',
    projectId: 'opportune-ego-460309-u3',
    storageBucket: 'opportune-ego-460309-u3.firebasestorage.app',
    androidClientId: '646227080671-r1bsheicnb7rt2rc76pnd7jhj0ragiu9.apps.googleusercontent.com',
    iosClientId: '646227080671-iehs55esvha9niqip06s3hnv4ibeik9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiohCeramicCafeClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxNJM0lIDY7Ge7E9eR2QjGG7qIWuPtkBc',
    appId: '1:646227080671:ios:3444c73d7e39c29415006a',
    messagingSenderId: '646227080671',
    projectId: 'opportune-ego-460309-u3',
    storageBucket: 'opportune-ego-460309-u3.firebasestorage.app',
    androidClientId: '646227080671-r1bsheicnb7rt2rc76pnd7jhj0ragiu9.apps.googleusercontent.com',
    iosClientId: '646227080671-iehs55esvha9niqip06s3hnv4ibeik9l.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiohCeramicCafeClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwsSXJbKu8JaI6xD5EJDSBHVUzz-Dz374',
    appId: '1:646227080671:web:1b3ce08ed6481b8715006a',
    messagingSenderId: '646227080671',
    projectId: 'opportune-ego-460309-u3',
    authDomain: 'opportune-ego-460309-u3.firebaseapp.com',
    storageBucket: 'opportune-ego-460309-u3.firebasestorage.app',
    measurementId: 'G-CC9PQCVC8P',
  );

}